### ISSUE TITLE
Create console command "init"

### ISSUE THREAD

**Issue by viktorprogger** [undine-project/undine#2]
**Use [Cobra](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md), #6**

When user calls `undine init`, he should get:
- a configuration file with example contents inside:
	```yaml
	templatePath: docs/template.html
	files:
	  - name: diagram-1
	    path: docs/diagram-1.md
	    title: Diagram Display Name
	```
- `docs` and `public` directories should be created with `.gitkeep` file inside each of them
- Also he should be asked, if he want to download a default template file. If yes, download [template.html](https://raw.githubusercontent.com/undine-project/undine/refs/heads/main/docs/template.html) should be downloaded.

Script also should check that there are no such directories and a config file. And do nothing in case if smthng exists.
Or we may do nothing if `init` script is run in a non-empty folder.
